import { User, Listing, LocalResource } from './types'

export const currentUser: User = {
  id: 'current',
  name: 'You',
  username: 'plantlover',
  avatar: '/images/plant-monstera.jpg',
  location: 'Portland, OR',
  bio: 'Passionate plant parent with a love for tropical houseplants and sustainable gardening.',
  joinedDate: 'March 2024',
  plantsShared: 12,
  rating: 4.9,
  badges: ['Top Trader', 'Green Thumb', 'Community Helper'],
}

export const users: User[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    username: 'greenthumb_sarah',
    avatar: '/images/plant-succulents.jpg',
    location: 'Portland, OR',
    bio: 'Urban gardener specializing in succulents and cacti. Love sharing plants with my community!',
    joinedDate: 'January 2023',
    plantsShared: 45,
    rating: 4.8,
    badges: ['Super Seller', 'Plant Expert'],
  },
  {
    id: '2',
    name: 'Marcus Johnson',
    username: 'veggie_marcus',
    avatar: '/images/plant-herbs.jpg',
    location: 'Portland, OR',
    bio: 'Growing vegetables and herbs in my backyard. Happy to share seeds and tips!',
    joinedDate: 'June 2023',
    plantsShared: 28,
    rating: 4.9,
    badges: ['Seed Saver', 'Helpful'],
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    username: 'flower_emily',
    avatar: '/images/community-garden.jpg',
    location: 'Portland, OR',
    bio: 'Flower enthusiast and community garden volunteer. Let\'s make our neighborhoods bloom!',
    joinedDate: 'April 2023',
    plantsShared: 67,
    rating: 5.0,
    badges: ['Top Trader', 'Community Star'],
  },
]

export const listings: Listing[] = [
  {
    id: '1',
    title: 'Beautiful Monstera Deliciosa - Large',
    description: 'Healthy 3-year-old Monstera with gorgeous fenestrations. Comes in a 10" terracotta pot. Perfect for bright indirect light. Must pick up.',
    price: 45,
    type: 'sale',
    category: 'plants',
    images: ['/images/plant-monstera.jpg'],
    user: users[0],
    location: '2.3 mi away',
    createdAt: '2 hours ago',
    likes: 24,
    comments: 8,
    condition: 'excellent',
    tags: ['houseplant', 'tropical', 'large'],
  },
  {
    id: '2',
    title: 'Heirloom Tomato Seeds - 5 Varieties',
    description: 'Saved from my garden! Includes Cherokee Purple, Brandywine, Green Zebra, Black Krim, and Yellow Pear. About 25 seeds each variety.',
    price: null,
    type: 'trade',
    category: 'seeds',
    images: ['/images/plant-seeds.jpg'],
    user: users[1],
    location: '0.8 mi away',
    createdAt: '5 hours ago',
    likes: 18,
    comments: 12,
    tags: ['heirloom', 'vegetable', 'organic'],
  },
  {
    id: '3',
    title: 'Succulent Arrangement Workshop Tips',
    description: 'Sharing my best tips for creating stunning succulent arrangements! Great for beginners. Ask me anything in the comments.',
    price: null,
    type: 'tip',
    category: 'tips',
    images: ['/images/plant-succulents.jpg'],
    user: users[0],
    location: 'Portland, OR',
    createdAt: '1 day ago',
    likes: 56,
    comments: 23,
    tags: ['beginner-friendly', 'tutorial', 'succulents'],
  },
  {
    id: '4',
    title: 'Garden Tool Set - Barely Used',
    description: 'Moving to an apartment and no longer need these. Includes trowel, cultivator, pruning shears, and gloves. All high quality.',
    price: 25,
    type: 'sale',
    category: 'tools',
    images: ['/images/garden-tools.jpg'],
    user: users[2],
    location: '3.1 mi away',
    createdAt: '3 days ago',
    likes: 12,
    comments: 4,
    condition: 'good',
    tags: ['starter-kit', 'quality'],
  },
  {
    id: '5',
    title: 'Fresh Herb Cuttings - Basil, Mint, Rosemary',
    description: 'Free cuttings from my herb garden! Ready to root in water. Pick up any day this week.',
    price: null,
    type: 'free',
    category: 'seeds',
    images: ['/images/plant-herbs.jpg'],
    user: users[1],
    location: '1.2 mi away',
    createdAt: '6 hours ago',
    likes: 34,
    comments: 15,
    tags: ['herbs', 'cuttings', 'kitchen-garden'],
  },
  {
    id: '6',
    title: 'Premium Organic Compost - 5 Gallons',
    description: 'Made from kitchen scraps and yard waste. Rich, dark, and full of nutrients. Bring your own container.',
    price: 10,
    type: 'sale',
    category: 'soil',
    images: ['/images/soil-compost.jpg'],
    user: users[2],
    location: '2.8 mi away',
    createdAt: '2 days ago',
    likes: 8,
    comments: 3,
    condition: 'excellent',
    tags: ['organic', 'sustainable', 'homemade'],
  },
]

export const localResources: LocalResource[] = [
  {
    id: '1',
    name: 'Green Valley Nursery',
    type: 'nursery',
    address: '1234 Garden Lane',
    distance: '1.2 mi',
    rating: 4.8,
    image: '/images/community-garden.jpg',
    hours: 'Mon-Sat 9am-6pm',
    phone: '(503) 555-0123',
  },
  {
    id: '2',
    name: 'Portland Community Garden',
    type: 'community-garden',
    address: '567 Oak Street',
    distance: '0.5 mi',
    rating: 4.9,
    image: '/images/community-garden.jpg',
    hours: 'Daily 6am-8pm',
  },
  {
    id: '3',
    name: 'Saturday Farmers Market',
    type: 'farmers-market',
    address: 'Downtown Square',
    distance: '2.0 mi',
    rating: 4.7,
    image: '/images/plant-herbs.jpg',
    hours: 'Sat 8am-2pm',
  },
  {
    id: '4',
    name: 'The Garden Center',
    type: 'garden-center',
    address: '890 Bloom Ave',
    distance: '3.5 mi',
    rating: 4.6,
    image: '/images/garden-tools.jpg',
    hours: 'Daily 8am-7pm',
    phone: '(503) 555-0456',
  },
  {
    id: '5',
    name: 'Urban Gardening Workshop',
    type: 'workshop',
    address: 'Community Center',
    distance: '1.8 mi',
    rating: 5.0,
    image: '/images/hero-plants.jpg',
    hours: 'First Saturday of month',
  },
]
